### ISSUE TITLE
Shorten the Discovery Server Status Mirror

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/fleet-operator#15]
### What would you like to be added?

Fleet currently mirrors the discovery server status to it's status, such as the manifest below:

```yaml
status:
  discoveryServerStatus:
    created: true
    status:
      configMapStatus:
        created: true
      connectionInfo:
        configMapName: my-fleet-discovery
        ip: 10.10.1.14
      phase: Ready
      podStatus:
        created: true
        ip: 10.10.1.14
        phase: Running
      serviceExportStatus:
        created: true
      serviceStatus:
        created: true
```

With use of federation (in hybrid fleets), resource status gets too long and complicated. Fleet should only mirror the field `status.phase` and an explanatory field like `status.reason` or `status.message` of DiscoveryServer.

### Why is this needed?

It's needed to make fleet status readable. Users can gather more detailed information about discovery server from the resource (DiscoveryServer) itself.
